name: Update Daily Site
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Update Model
        run: node .scripts/getfolders.mjs
      - name: Commit to Repository
        run: |
          git config --global user.name 'daily-site'
          git config --global user.email 'daily-site'
          git add index.html
          git commit -m "[GHA] Model Update"
          git push